### ISSUE TITLE
Case sensitivity 

### ISSUE THREAD

**Issue by JayBizzle** [imliam/php-unique-gmail-address#5]
I haven’t fully looked at the code, but `test@gmail.com` is the same as `TEST@gmail.com`

I’m not sure if this package allows for that 🤔

**Comment by szepeviktor** [comment]
Hello @JayBizzle! This allows you to do that and really anything :)
https://github.com/szepeviktor/unique-email-address/blob/master/src/Rules/LowercaseRule.php
