### ISSUE TITLE
usage of laravel rule

### ISSUE THREAD

**Issue by stephanus-tantiono** [imliam/php-unique-gmail-address#8]
Hi, I'm trying to use this at my validator,

````
'email' => [new UniqueGmailAddressRule()]
````

but it doesnt work, 
example : example@gmail.com; ex+ample@gmail.com still pass

**Comment by imliam** [comment]
I've just tested the generated query in a MySQL database and it appears to be working as intended. Are you using a different database driver or different structure for the users table (users table, email column)?

Feel free to open a new ticket if this is still an issue.
